# Generated by Django 5.1 on 2024-08-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_downvote_count_post_upvote_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='total_likes',
        ),
    ]
