# Generated by Django 5.1 on 2024-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_remove_comment_total_likes_remove_post_total_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='type',
            field=models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=None, null=True),
        ),
    ]
